version: '3'

networks:
   default:
     driver: bridge

services:
  angular:
    build: ./AngularApp
    ports:
      - "5555:4200"

  express:
    build: ./NodeJS
    ports:
      - "3000:3000"
    links:
      - database

  database:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume: